/* =========================================================================
   PRODUCTS.JS
   All product data lives here as one PRODUCTS array. Every part of the
   site (homepage, catalog, search, product modal) reads from it.

   Generated from manage-products.html on 2026-09-27.
   To keep managing products, open manage-products.html again and re-upload
   this file when you're done — it always starts from whatever products.js
   is currently on the server.
   ========================================================================= */

const PRODUCTS = [
  {
    id: "refinex-botx-100",
    name: "REFINEX Botulinum Toxin (100 Units)",
    brand: "refinex",
    category: "botox",
    subcategory: "Standard Vial",
    price: 1100,
    description: "A standard-vial botulinum toxin type A formulation for the treatment of dynamic facial wrinkles and hyperhidrosis.",
    image: "img/products/refinex-botx-100.webp",
    gallery: ["img/products/refinex-botx-100-2.webp"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-01-10",
    tags: ["botox", "toxin", "wrinkles", "hyperhidrosis", "100 units"]
  },
  {
    id: "metox-100u",
    name: "METOX Botulinum Toxin (100 Units)",
    brand: "metox",
    category: "botox",
    subcategory: "Standard Vial",
    price: 1400,
    description: "A 100-unit botulinum toxin type A vial formulated for precise treatment of dynamic wrinkles.",
    image: "img/products/metox-100u.webp",
    gallery: ["img/products/metox-100u-2.webp"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-01-15",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "dysport-500u",
    name: "Dysport Botulinum Toxin (500 Units)",
    brand: "dysport",
    category: "botox",
    subcategory: "Standard Vial",
    price: 2500,
    description: "A widely used botulinum toxin type A formulation for wrinkle treatment and management of excessive sweating.",
    image: "img/products/dysport-500u.webp",
    gallery: ["img/products/dysport-500u-2.webp"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-01-20",
    tags: ["botox", "toxin", "wrinkles", "hyperhidrosis", "500 units"]
  },
  {
    id: "evetox-100unit",
    name: "Eve Tox Botulinum Toxin (100 Units)",
    brand: "evetox",
    category: "botox",
    subcategory: "Standard Vial",
    price: 1900,
    description: "A botulinum toxin type A vial designed to smooth dynamic facial lines and refresh expression.",
    image: "img/products/evetox-100unit.webp",
    gallery: ["img/products/evetox-100unit-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-25",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "nabota-100unit",
    name: "Nabota Botulinum Toxin (100 Units)",
    brand: "nabota",
    category: "botox",
    subcategory: "Standard Vial",
    price: 2200,
    description: "A 100-unit botulinum toxin type A formulation for dynamic wrinkle correction.",
    image: "img/products/nabota-100unit.webp",
    gallery: ["img/products/nabota-100unit-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-30",
    tags: ["botox", "toxin", "wrinkles", "100 units"]
  },
  {
    id: "demure-ultra-10ml",
    name: "Demure Ultra Dermal Filler (10 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    price: 3000,
    description: "A hyaluronic-acid gel designed for facial and body volumizing and contouring.",
    image: "img/products/demure-ultra-10ml.webp",
    gallery: ["img/products/demure-ultra-10ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-04",
    tags: ["filler", "hyaluronic acid", "volumizing", "10 ml"]
  },
  {
    id: "demure-grand-10ml",
    name: "Demure Grand Dermal Filler (10 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    price: 3000,
    description: "A higher-volume hyaluronic-acid gel for facial and body contouring procedures.",
    image: "img/products/demure-grand-10ml.webp",
    gallery: ["img/products/demure-grand-10ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-09",
    tags: ["filler", "hyaluronic acid", "volumizing", "10 ml"]
  },
  {
    id: "dermofil-hv",
    name: "Dermofil HV Dermal Filler (1 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "High Viscosity",
    price: 3000,
    description: "A high-viscosity hyaluronic-acid filler intended for deep structural placement.",
    image: "img/products/dermofil-hv.webp",
    gallery: ["img/products/dermofil-hv-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-14",
    tags: ["filler", "high viscosity", "hyaluronic acid", "1 ml"]
  },
  {
    id: "dermofil-volumizer",
    name: "Dermofil Volumizer (1 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    price: 3200,
    description: "A cohesive volumizing gel formulated for mid-face and structural support.",
    image: "img/products/dermofil-volumizer.webp",
    gallery: ["img/products/dermofil-volumizer-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-19",
    tags: ["filler", "volumizer", "hyaluronic acid", "1 ml"]
  },
  {
    id: "hyamax-10ml-contour",
    name: "Hyamax Contour White Label (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Contour",
    price: 2800,
    description: "A white-label hyaluronic-acid gel for facial contouring and body sculpting.",
    image: "img/products/hyamax-10ml-contour.webp",
    gallery: ["img/products/hyamax-10ml-contour-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-24",
    tags: ["filler", "contour", "white label", "10 ml"]
  },
  {
    id: "hyamax-10ml-contour-c",
    name: "Hyamax Contour C (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Contour",
    price: 3000,
    description: "A hyaluronic-acid gel formulated for definition of larger contouring areas.",
    image: "img/products/hyamax-10ml-contour-c.webp",
    gallery: ["img/products/hyamax-10ml-contour-c-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-01",
    tags: ["filler", "contour", "body", "10 ml"]
  },
  {
    id: "hyamax-10ml-volumizer",
    name: "Hyamax Volumizer (10 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    price: 3000,
    description: "A high-capacity volumizing hyaluronic-acid gel for facial and body use.",
    image: "img/products/hyamax-10ml-volumizer.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-06",
    tags: ["filler", "volumizer", "hyaluronic acid", "10 ml"]
  },
  {
    id: "master-treat-extreme-black",
    name: "Master Treat Extreme (Black) (1 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "Extreme Density",
    price: 2500,
    description: "An extreme-density gel formulated for large-area contouring and definition.",
    image: "img/products/master-treat-extreme-black.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-11",
    tags: ["filler", "extreme density", "contour", "1 ml"]
  },
  {
    id: "audrey-m-blue",
    name: "Audrey Medium Viscosity (Blue) (1 ml)",
    brand: "audrey",
    category: "dermal-fillers",
    subcategory: "Medium Viscosity",
    price: 2500,
    description: "A medium-viscosity hyaluronic-acid filler for balanced volumizing results.",
    image: "img/products/audrey-m-blue.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-16",
    tags: ["filler", "medium viscosity", "1 ml"]
  },
  {
    id: "audrey-h-black",
    name: "Audrey High Viscosity (Black) (1 ml)",
    brand: "audrey",
    category: "dermal-fillers",
    subcategory: "High Viscosity",
    price: 2500,
    description: "A high-viscosity hyaluronic-acid filler for structural definition.",
    image: "img/products/audrey-h-black.webp",
    gallery: ["img/products/audrey-h-black-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-21",
    tags: ["filler", "high viscosity", "1 ml"]
  },
  {
    id: "revolax-subq",
    name: "Revolax Sub-Q (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Sub-Q",
    price: 1100,
    description: "A dense hyaluronic-acid gel formulated for deep sub-dermal volumizing.",
    image: "img/products/revolax-subq.webp",
    gallery: ["img/products/revolax-subq-2.webp"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-03-26",
    tags: ["filler", "sub-q", "hyaluronic acid", "1 ml"]
  },
  {
    id: "master-treat-standard-white",
    name: "Master Treat Standard (White) (1 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "Standard Density",
    price: 2500,
    description: "A standard-density hyaluronic-acid gel for general facial revitalization and fine-line improvement.",
    image: "img/products/master-treat-standard-white.webp",
    gallery: ["img/products/master-treat-standard-white-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-31",
    tags: ["filler", "standard density", "1 ml"]
  },
  {
    id: "deneb-classic-h",
    name: "DeneB Classic-H (1 ml)",
    brand: "deneb",
    category: "dermal-fillers",
    subcategory: "High Density",
    price: 1900,
    description: "A high-density filler intended for revitalization and improvement of facial lines.",
    image: "img/products/deneb-classic-h.webp",
    gallery: ["img/products/deneb-classic-h-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-05",
    tags: ["filler", "high density", "1 ml"]
  },
  {
    id: "sedyfill-60cc",
    name: "Sedyfill 60CC (60 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    price: 5500,
    description: "A large-format hyaluronic-acid gel for body contouring and volumizing.",
    image: "img/products/sedyfill-60cc.webp",
    gallery: ["img/products/sedyfill-60cc-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-10",
    tags: ["filler", "body", "contouring", "60 cc"]
  },
  {
    id: "sedyfill-80cc",
    name: "Sedyfill 80CC (80 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    price: 6500,
    description: "A large-format hyaluronic-acid gel for body contouring and volumizing.",
    image: "img/products/sedyfill-80cc.webp",
    gallery: ["img/products/sedyfill-80cc-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-15",
    tags: ["filler", "body", "contouring", "80 cc"]
  },
  {
    id: "sedyfill-100cc",
    name: "Sedyfill 100CC (100 cc)",
    brand: "sedyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    price: 7500,
    description: "A large-format hyaluronic-acid gel for extensive body contouring procedures.",
    image: "img/products/sedyfill-100cc.webp",
    gallery: ["img/products/sedyfill-100cc-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-20",
    tags: ["filler", "body", "contouring", "100 cc"]
  },
  {
    id: "celosome-soft",
    name: "Celosome Soft Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Soft Density",
    price: 1500,
    description: "A soft-density filler suited to superficial lines around the eyes and lips.",
    image: "img/products/celosome-soft.webp",
    gallery: ["img/products/celosome-soft-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-25",
    tags: ["filler", "soft density", "fine lines", "1 ml"]
  },
  {
    id: "celosome-mid",
    name: "Celosome Medium Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Medium Density",
    price: 1500,
    description: "A medium-density filler for balanced facial revitalization.",
    image: "img/products/celosome-mid.webp",
    gallery: ["img/products/celosome-mid-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-30",
    tags: ["filler", "medium density", "1 ml"]
  },
  {
    id: "celosome-strong",
    name: "Celosome Strong Density (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Strong Density",
    price: 1500,
    description: "A strong-density filler formulated for larger-area contouring and definition.",
    image: "img/products/celosome-strong.webp",
    gallery: ["img/products/celosome-strong-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-05",
    tags: ["filler", "strong density", "contour", "1 ml"]
  },
  {
    id: "celosome-implant",
    name: "Celosome Implant Grade (1 ml)",
    brand: "celosome",
    category: "dermal-fillers",
    subcategory: "Implant Grade",
    price: 1500,
    description: "An implant-grade filler intended for deep structural placement.",
    image: "img/products/celosome-implant.webp",
    gallery: ["img/products/celosome-implant-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-10",
    tags: ["filler", "implant grade", "1 ml"]
  },
  {
    id: "revolax-deep",
    name: "Revolax Deep (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Deep Density",
    price: 1100,
    description: "A deep-density hyaluronic-acid gel for superficial-to-deep line correction around the eyes and lips.",
    image: "img/products/revolax-deep.webp",
    gallery: ["img/products/revolax-deep-2.webp"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-05-15",
    tags: ["filler", "deep density", "1 ml"]
  },
  {
    id: "sculptra-white",
    name: "Sculptra (PLLA) (1 vial)",
    brand: "sculptra",
    category: "dermal-fillers",
    subcategory: "Poly-L-Lactic Acid",
    price: 5000,
    description: "A poly-L-lactic acid (PLLA) biostimulator for gradual, long-lasting collagen stimulation.",
    image: "img/products/sculptra-white.webp",
    gallery: ["img/products/sculptra-white-2.webp"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-05-20",
    tags: ["filler", "plla", "collagen stimulator", "1 vial"]
  },
  {
    id: "olidia-plla",
    name: "Olidia PLLA Bio-stimulator (1 vial)",
    brand: "olidia",
    category: "dermal-fillers",
    subcategory: "PLLA Bio-stimulator",
    price: 6500,
    description: "A PLLA-based biostimulator formulated for long-lasting collagen stimulation.",
    image: "img/products/olidia-plla.webp",
    gallery: ["img/products/olidia-plla-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-25",
    tags: ["filler", "plla", "collagen stimulator", "1 vial"]
  },
  {
    id: "vom-intense",
    name: "VOM Intense HA Density (1 ml)",
    brand: "vom",
    category: "dermal-fillers",
    subcategory: "Intense HA Density",
    price: 2000,
    description: "An intense-density hyaluronic-acid filler for pronounced volumizing and contouring.",
    image: "img/products/vom-intense.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-30",
    tags: ["filler", "intense density", "hyaluronic acid", "1 ml"]
  },
  {
    id: "liporase-1500iu",
    name: "Liporase Hyaluronidase (1500 IU)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Hyaluronidase",
    price: 3000,
    description: "A hyaluronidase enzyme preparation used to dissolve hyaluronic-acid filler.",
    image: "img/products/liporase-1500iu.webp",
    gallery: ["img/products/liporase-1500iu-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-04",
    tags: ["hyaluronidase", "dissolving enzyme", "1500 iu"]
  },
  {
    id: "premium-2ml",
    name: "Premium Filler (2 ml)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Volumizing & Contouring",
    price: 3800,
    description: "A hyaluronic-acid gel designed for facial volumizing and contouring.",
    image: "img/products/premium-2ml.webp",
    gallery: ["img/products/premium-2ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-09",
    tags: ["filler", "hyaluronic acid", "2 ml"]
  },
  {
    id: "hyamax-lips-1ml",
    name: "Hyamax Lips (1 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Fine Lines",
    price: 3500,
    description: "A hyaluronic-acid gel formulated for lip enhancement and superficial lines around the mouth.",
    image: "img/products/hyamax-lips-1ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-14",
    tags: ["filler", "lips", "fine lines", "1 ml"]
  },
  {
    id: "richesse-soft-1ml",
    name: "Richesse Soft (1 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Fine Lines",
    price: 1900,
    description: "A soft-formulation filler for superficial lines around the eyes and lips.",
    image: "img/products/richesse-soft-1ml.webp",
    gallery: ["img/products/richesse-soft-1ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-19",
    tags: ["filler", "soft", "fine lines", "1 ml"]
  },
  {
    id: "richesse-deep-1ml",
    name: "Richesse Deep (1 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Revitalization",
    price: 2300,
    description: "A deep-formulation filler for facial revitalization and line improvement.",
    image: "img/products/richesse-deep-1ml.webp",
    gallery: ["img/products/richesse-deep-1ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-24",
    tags: ["filler", "deep", "revitalization", "1 ml"]
  },
  {
    id: "dermofil-volumizer-2ml",
    name: "Dermofil Volumizer (2 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    price: 4200,
    description: "A cohesive volumizing gel formulated for total-face contouring.",
    image: "img/products/dermofil-volumizer-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-29",
    tags: ["filler", "volumizer", "2 ml"]
  },
  {
    id: "vom-light",
    name: "VOM Light Viscosity (1 ml)",
    brand: "vom",
    category: "dermal-fillers",
    subcategory: "Light Viscosity",
    price: 1900,
    description: "A light-viscosity hyaluronic-acid gel for delicate facial areas.",
    image: "img/products/vom-light.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-04",
    tags: ["filler", "light viscosity", "1 ml"]
  },
  {
    id: "hyamax-extra-deep-2ml",
    name: "Hyamax Extra Deep (2 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Collagen Stimulator",
    price: 4200,
    description: "A long-lasting collagen-stimulating formulation for deep structural support.",
    image: "img/products/hyamax-extra-deep-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-09",
    tags: ["filler", "collagen stimulator", "deep", "2 ml"]
  },
  {
    id: "hyamax-extra-deep-2ml-red",
    name: "Hyamax Extra Deep Red (2 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Collagen Stimulator",
    price: 4200,
    description: "A long-lasting collagen-stimulating formulation for deep structural support.",
    image: "img/products/hyamax-extra-deep-2ml-red.webp",
    gallery: ["img/products/hyamax-extra-deep-2ml-red-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-14",
    tags: ["filler", "collagen stimulator", "deep", "2 ml"]
  },
  {
    id: "hyamax-volumizer-2ml",
    name: "Hyamax Volumizer (2 ml x 2)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Volumizer",
    price: 3500,
    description: "A volumizing hyaluronic-acid gel for facial and body contouring.",
    image: "img/products/hyamax-volumizer-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-19",
    tags: ["filler", "volumizer", "2 ml"]
  },
  {
    id: "hyamax-caha-1ml",
    name: "Hyamax Calcium Hydroxyapatite (1 ml)",
    brand: "hyamax",
    category: "dermal-fillers",
    subcategory: "Calcium Hydroxyapatite",
    price: 4000,
    description: "A calcium-hydroxyapatite formulation for structural volumizing and contouring.",
    image: "img/products/hyamax-caha-1ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-24",
    tags: ["filler", "calcium hydroxyapatite", "1 ml"]
  },
  {
    id: "volume-red-ha",
    name: "Volumizing HA Red (1 ml)",
    brand: "premium",
    category: "dermal-fillers",
    subcategory: "Volumizing HA",
    price: 1800,
    description: "A red-labeled volumizing hyaluronic-acid gel for facial contouring.",
    image: "img/products/volume-red-ha.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-29",
    tags: ["filler", "volumizing", "hyaluronic acid", "1 ml"]
  },
  {
    id: "revolax-fine",
    name: "Revolax Fine (1 ml)",
    brand: "revolax",
    category: "dermal-fillers",
    subcategory: "Fine Viscosity",
    price: 1100,
    description: "A fine-viscosity filler formulated for superficial fine lines.",
    image: "img/products/revolax-fine.webp",
    gallery: ["img/products/revolax-fine-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-03",
    tags: ["filler", "fine viscosity", "fine lines", "1 ml"]
  },
  {
    id: "eptq-10ml",
    name: "E.P.T.Q Large Volume (10 ml)",
    brand: "eptq",
    category: "dermal-fillers",
    subcategory: "Large Volume",
    price: 6500,
    description: "A large-volume hyaluronic-acid gel for extensive body contouring.",
    image: "img/products/eptq-10ml.webp",
    gallery: ["img/products/eptq-10ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-08",
    tags: ["filler", "large volume", "body", "10 ml"]
  },
  {
    id: "richesse-glam-60ml",
    name: "Richesse Glam Body Filler (60 ml)",
    brand: "richesse",
    category: "dermal-fillers",
    subcategory: "Body Filler",
    price: 4500,
    description: "A large-format body filler formulated for body contouring procedures.",
    image: "img/products/richesse-glam-60ml.webp",
    gallery: ["img/products/richesse-glam-60ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-13",
    tags: ["filler", "body", "glam", "60 ml"]
  },
  {
    id: "bella-ha-2x1ml-fine",
    name: "Bella HA Filler Fine (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    price: 2200,
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "img/products/bella-ha-2x1ml-fine.webp",
    gallery: ["img/products/bella-ha-2x1ml-fine-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-18",
    tags: ["filler", "bella", "fine", "2 x 1 ml"]
  },
  {
    id: "bella-ha-2x1ml-deep",
    name: "Bella HA Filler Deep (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    price: 2200,
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "img/products/bella-ha-2x1ml-deep.webp",
    gallery: ["img/products/bella-ha-2x1ml-deep-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-23",
    tags: ["filler", "bella", "deep", "2 x 1 ml"]
  },
  {
    id: "bella-ha-2x1ml-derm",
    name: "Bella HA Filler Derm (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    price: 2200,
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "img/products/bella-ha-2x1ml-derm.webp",
    gallery: ["img/products/bella-ha-2x1ml-derm-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-28",
    tags: ["filler", "bella", "derm", "2 x 1 ml"]
  },
  {
    id: "bella-ha-1ml-fine",
    name: "Bella HA Filler Fine (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    price: 1400,
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "img/products/bella-ha-1ml-fine.webp",
    gallery: ["img/products/bella-ha-1ml-fine-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-02",
    tags: ["filler", "bella", "fine", "1 ml"]
  },
  {
    id: "bella-ha-1ml-deep",
    name: "Bella HA Filler Deep (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    price: 1400,
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "img/products/bella-ha-2x1ml-deep.webp",
    gallery: ["img/products/bella-ha-2x1ml-deep-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-07",
    tags: ["filler", "bella", "deep", "1 ml"]
  },
  {
    id: "bella-ha-1ml-derm",
    name: "Bella HA Filler Derm (1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    price: 1400,
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "img/products/bella-ha-1ml-derm.webp",
    gallery: ["img/products/bella-ha-1ml-derm-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-12",
    tags: ["filler", "bella", "derm", "1 ml"]
  },
  {
    id: "bella-ha-2ml-fine",
    name: "Bella HA Filler Fine (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Fine",
    price: 2000,
    description: "A fine-formulation hyaluronic-acid filler for delicate facial areas.",
    image: "img/products/bella-ha-2x1ml-fine.webp",
    gallery: ["img/products/bella-ha-2x1ml-fine-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-17",
    tags: ["filler", "bella", "fine", "2 ml"]
  },
  {
    id: "bella-ha-2ml-deep",
    name: "Bella HA Filler Deep (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    price: 2000,
    description: "A deep-formulation hyaluronic-acid filler for structural volumizing.",
    image: "img/products/bella-ha-2ml-deep.webp",
    gallery: ["img/products/bella-ha-2ml-deep-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-22",
    tags: ["filler", "bella", "deep", "2 ml"]
  },
  {
    id: "bella-ha-2ml-derm",
    name: "Bella HA Filler Derm (2 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    price: 2000,
    description: "A dermal-layer hyaluronic-acid filler for mid-depth placement.",
    image: "img/products/bella-ha-2ml-derm.webp",
    gallery: ["img/products/bella-ha-1ml-derm-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-27",
    tags: ["filler", "bella", "derm", "2 ml"]
  },
  {
    id: "bella-red-lips-2x1ml",
    name: "Bella Red Lips (2 x 1 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Lips",
    price: 3500,
    description: "A hyaluronic-acid filler formulated specifically for lip enhancement.",
    image: "img/products/bella-red-lips-2x1ml.webp",
    featured: true,
    bestseller: true,
    dateAdded: "2026-10-02",
    tags: ["filler", "bella", "lips", "2 x 1 ml"]
  },
  {
    id: "bella-ha-10ml-subskin",
    name: "Bella HA Filler Sub-Skin (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Sub-Skin",
    price: 3000,
    description: "A large-format sub-skin hyaluronic-acid filler for body use.",
    image: "img/products/bella-ha-10ml-subskin.webp",
    gallery: ["img/products/bella-ha-10ml-subskin-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-07",
    tags: ["filler", "bella", "sub-skin", "body", "10 ml"]
  },
  {
    id: "bella-ha-10ml-deep",
    name: "Bella HA Filler Deep (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Deep",
    price: 3000,
    description: "A large-format deep hyaluronic-acid filler for body contouring.",
    image: "img/products/bella-ha-10ml-deep.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-12",
    tags: ["filler", "bella", "deep", "body", "10 ml"]
  },
  {
    id: "bella-ha-10ml-derm",
    name: "Bella HA Filler Derm (10 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Derm",
    price: 3000,
    description: "A large-format dermal-layer hyaluronic-acid filler for body use.",
    image: "img/products/bella-ha-10ml-derm.webp",
    gallery: ["img/products/bella-ha-1ml-derm-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-17",
    tags: ["filler", "bella", "derm", "body", "10 ml"]
  },
  {
    id: "bella-body-50ml",
    name: "Bella Body HA Filler (50 ml)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    price: 5500,
    description: "A large-format hyaluronic-acid body filler for extensive contouring.",
    image: "img/products/bella-body-50ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-22",
    tags: ["filler", "bella", "body", "50 ml"]
  },
  {
    id: "bella-body-60ml-26mg",
    name: "Bella Body HA Filler 26mg/ml (60 ml (26 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    price: 5500,
    description: "A concentrated hyaluronic-acid body filler for extensive contouring.",
    image: "img/products/bella-body-50ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-10-27",
    tags: ["filler", "bella", "body", "60 ml (26 mg/ml)"]
  },
  {
    id: "bella-body-100ml-26mg",
    name: "Bella Body HA Filler 26mg/ml (100 ml (26 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    price: 7500,
    description: "A large-format concentrated hyaluronic-acid body filler.",
    image: "img/products/bella-body-100ml-26mg.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-11-01",
    tags: ["filler", "bella", "body", "100 ml (26 mg/ml)"]
  },
  {
    id: "bella-body-60ml-18mg",
    name: "Bella Body HA Filler 18mg/ml (60 ml (18 mg/ml))",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Body",
    price: 4500,
    description: "A hyaluronic-acid body filler formulated for body contouring.",
    image: "img/products/bella-body-60ml-18mg.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-10",
    tags: ["filler", "bella", "body", "60 ml (18 mg/ml)"]
  },
  {
    id: "bella-plla-stimulator",
    name: "Bella PLLA Stimulator (1 vial)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "PLLA Stimulator",
    price: 3000,
    description: "A poly-L-lactic acid biostimulator for long-lasting collagen stimulation.",
    image: "img/products/bella-plla-stimulator.webp",
    gallery: ["img/products/bella-plla-stimulator-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-15",
    tags: ["filler", "bella", "plla", "collagen stimulator", "1 vial"]
  },
  {
    id: "bella-calcium-filler",
    name: "Bella Calcium Filler (1 vial)",
    brand: "bella",
    category: "dermal-fillers",
    subcategory: "Calcium Hydroxyapatite",
    price: 3500,
    description: "A calcium-hydroxyapatite filler for structural volumizing and contouring.",
    image: "img/products/bella-calcium-filler.webp",
    gallery: ["img/products/bella-calcium-filler-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-20",
    tags: ["filler", "bella", "calcium hydroxyapatite", "1 vial"]
  },
  {
    id: "hadurage-joint-2ml",
    name: "Hadurage Joint Filler (2 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Intra-Articular",
    price: 3000,
    description: "An intra-articular hyaluronic-acid preparation for joint viscosupplementation.",
    image: "img/products/hadurage-joint-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-25",
    tags: ["joint filler", "intra-articular", "2 ml"]
  },
  {
    id: "hadurage-joint-3ml",
    name: "Hadurage Joint Filler (3 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Intra-Articular",
    price: 3800,
    description: "An intra-articular hyaluronic-acid preparation for joint viscosupplementation.",
    image: "img/products/hadurage-joint-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-01-30",
    tags: ["joint filler", "intra-articular", "3 ml"]
  },
  {
    id: "hadurage-red-lips-2x1ml",
    name: "Hadurage Red Lips (2 x 1 ml)",
    brand: "hadurage",
    category: "dermal-fillers",
    subcategory: "Lips",
    price: 3000,
    description: "A hyaluronic-acid filler formulated specifically for lip enhancement.",
    image: "img/products/hadurage-red-lips-2x1ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-04",
    tags: ["filler", "hadurage", "lips", "2 x 1 ml"]
  },
  {
    id: "maxyfill-70cc",
    name: "Maxyfill Body (70 cc)",
    brand: "maxyfill",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    price: 7000,
    description: "A large-format hyaluronic-acid gel for extensive body contouring.",
    image: "img/products/maxyfill-70cc.webp",
    gallery: ["img/products/maxyfill-70cc-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-09",
    tags: ["filler", "body", "contouring", "70 cc"]
  },
  {
    id: "dermofil-volmatic-2ml",
    name: "Dermofil Volmatic (2 ml)",
    brand: "dermofil",
    category: "dermal-fillers",
    subcategory: "Volmatic",
    price: 3800,
    description: "A cohesive volumizing gel formulated for structural facial support.",
    image: "img/products/dermofil-volmatic-2ml.webp",
    gallery: ["img/products/dermofil-volmatic-2ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-19",
    tags: ["filler", "volmatic", "2 ml"]
  },
  {
    id: "master-treat-20ml",
    name: "Master Treat High Volume (20 ml)",
    brand: "master-treat",
    category: "dermal-fillers",
    subcategory: "High Volume",
    price: 9000,
    description: "A high-volume gel formulated for extensive body contouring.",
    image: "img/products/master-treat-20ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-02-24",
    tags: ["filler", "high volume", "body", "20 ml"]
  },
  {
    id: "bde-beaute-60cc",
    name: "BDE Beauté Body (60 cc)",
    brand: "bde-beaute",
    category: "dermal-fillers",
    subcategory: "Body Contouring",
    price: 4500,
    description: "A large-format body filler for contouring procedures.",
    image: "img/products/bde-beaute-60cc.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-01",
    tags: ["filler", "body", "contouring", "60 cc"]
  },
  {
    id: "demure-ultra-20ml-k",
    name: "Demure Ultra K (20 ml)",
    brand: "demure",
    category: "dermal-fillers",
    subcategory: "Ultra",
    price: 3000,
    description: "A large-format hyaluronic-acid gel for body volumizing and contouring.",
    image: "img/products/demure-ultra-20ml-k.webp",
    gallery: ["img/products/demure-ultra-20ml-k-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-06",
    tags: ["filler", "ultra", "body", "20 ml"]
  },
  {
    id: "eptq-s500",
    name: "E.P.T.Q S500 Structural",
    brand: "eptq",
    category: "dermal-fillers",
    subcategory: "Structural",
    price: 4500,
    description: "A structural collagen-stimulating formulation for long-lasting facial support.",
    image: "img/products/eptq-s500.webp",
    gallery: ["img/products/eptq-s500-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-11",
    tags: ["filler", "structural", "collagen stimulator", "s500"]
  },
  {
    id: "hyaron-2-5ml",
    name: "Hyaron Sodium Hyaluronate (2.5 ml)",
    brand: "hyaron",
    category: "skin-boosters",
    subcategory: "Sodium Hyaluronate",
    price: 5000,
    description: "A sodium-hyaluronate skin booster formulated to support hydration and skin quality.",
    image: "img/products/hyaron-2-5ml.webp",
    gallery: ["https://cosmetix.eu/hpeciai/a0fe385de2d23a407afbfacc41fea23e/eng_pl_Hyaron-2-5ml-433_1_1.jpg"],
    featured: true,
    bestseller: true,
    dateAdded: "2026-03-16",
    tags: ["skin booster", "hyaluronic acid", "hydration", "2.5 ml"]
  },
  {
    id: "aqua-exosome",
    name: "Aqua Exosome Complex (1 vial)",
    brand: "aqua",
    category: "skin-boosters",
    subcategory: "Exosome Complex",
    price: 7000,
    description: "An exosome-complex skin booster formulated to support skin revitalization.",
    image: "img/products/aqua-exosome.webp",
    gallery: ["img/products/aqua-exosome-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-21",
    tags: ["skin booster", "exosome", "1 vial"]
  },
  {
    id: "exo-active",
    name: "Exo Active Exosomes (1 vial)",
    brand: "exo",
    category: "skin-boosters",
    subcategory: "Exosomes",
    price: 1900,
    description: "An active exosome preparation formulated for skin revitalization treatments.",
    image: "img/products/exo-active.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-26",
    tags: ["skin booster", "exosome", "1 vial"]
  },
  {
    id: "regloray-pdrn",
    name: "Regloray PDRN (1 vial)",
    brand: "regloray",
    category: "skin-boosters",
    subcategory: "PDRN Polynucleotide",
    price: 2100,
    description: "A PDRN (polynucleotide) skin booster formulated to support skin repair and quality.",
    image: "img/products/regloray-pdrn.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-03-31",
    tags: ["skin booster", "pdrn", "1 vial"]
  },
  {
    id: "mesoheal-amber-glow",
    name: "Mesoheal Amber Glow (1 vial)",
    brand: "mesoheal",
    category: "skin-boosters",
    subcategory: "Succinic Acid + HA",
    price: 6500,
    description: "A succinic-acid and hyaluronic-acid complex formulated to support skin radiance.",
    image: "img/products/mesoheal-amber-glow.webp",
    gallery: ["img/products/mesoheal-amber-glow-2.webp"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-04-05",
    tags: ["skin booster", "succinic acid", "glow", "1 vial"]
  },
  {
    id: "dermofil-super-hydra",
    name: "Dermofil Super Hydra (1 vial)",
    brand: "dermofil",
    category: "skin-boosters",
    subcategory: "Super Hydra Complex",
    price: 1900,
    description: "A hydration-focused complex skin booster for improved skin moisture retention.",
    image: "img/products/dermofil-super-hydra.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-10",
    tags: ["skin booster", "hydration", "1 vial"]
  },
  {
    id: "rrs-long-lasting-3ml",
    name: "RRS Long Lasting (3 ml)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "HA + Amino Acids",
    price: 3500,
    description: "A hyaluronic-acid and amino-acid complex formulated for long-lasting skin revitalization.",
    image: "img/products/rrs-long-lasting-3ml.webp",
    gallery: ["img/products/rrs-long-lasting-3ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-15",
    tags: ["skin booster", "amino acids", "hyaluronic acid", "3 ml"]
  },
  {
    id: "rrs-hyalift-750-active",
    name: "RRS Hyalift Pro Active (750 mg)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "Pure HA",
    price: 3000,
    description: "A pure hyaluronic-acid skin booster formulated for skin hydration and quality.",
    image: "img/products/rrs-hyalift-750-active.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-20",
    tags: ["skin booster", "hyaluronic acid", "750 mg"]
  },
  {
    id: "booster-starter-kit",
    name: "Multi-Component Booster Kit (1 kit)",
    brand: "clinic-select",
    category: "skin-boosters",
    subcategory: "Starter Kit",
    price: 3500,
    description: "A multi-component starter kit for skin-booster treatment sessions.",
    image: "",
    featured: false,
    bestseller: false,
    dateAdded: "2026-04-25",
    tags: ["skin booster", "kit", "1 kit"]
  },
  {
    id: "jalupro-super-hydro",
    name: "Jalupro Super Hydro (1 vial)",
    brand: "jalupro",
    category: "skin-boosters",
    subcategory: "HA + Amino Acids + Peptides",
    price: 4000,
    description: "A hyaluronic-acid, amino-acid and peptide complex for skin revitalization.",
    image: "img/products/jalupro-super-hydro.webp",
    gallery: ["img/products/jalupro-super-hydro-2.webp"],
    featured: true,
    bestseller: false,
    dateAdded: "2026-04-30",
    tags: ["skin booster", "amino acids", "peptides", "1 vial"]
  },
  {
    id: "bella-skin-booster-2-20ml",
    name: "Bella Skin Booster (2 ml / 20 ml)",
    brand: "bella",
    category: "skin-boosters",
    subcategory: "Skin Booster",
    price: 1900,
    description: "A hyaluronic-acid skin booster available in clinic and multi-session formats.",
    image: "img/products/bella-skin-booster-2-20ml.webp",
    gallery: ["img/products/bella-skin-booster-2-20ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-05",
    tags: ["skin booster", "bella", "2 ml / 20 ml"]
  },
  {
    id: "bella-hl-2ml",
    name: "Bella H+L (2 ml)",
    brand: "bella",
    category: "skin-boosters",
    subcategory: "High & Low HA",
    price: 1900,
    description: "A dual-molecular-weight (high and low HA) skin booster for layered hydration.",
    image: "img/products/bella-hl-2ml.webp",
    gallery: ["img/products/bella-hl-2ml-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-10",
    tags: ["skin booster", "bella", "hyaluronic acid", "2 ml"]
  },
  {
    id: "hadurage-pdrn-2ml",
    name: "Hadurage PDRN Skin Booster (2 ml)",
    brand: "hadurage",
    category: "skin-boosters",
    subcategory: "PDRN",
    price: 2100,
    description: "A PDRN skin booster formulated to support skin repair and revitalization.",
    image: "img/products/hadurage-pdrn-2ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-15",
    tags: ["skin booster", "pdrn", "hadurage", "2 ml"]
  },
  {
    id: "nithya-collagen-powder",
    name: "Nithya Collagen Powder (1 vial)",
    brand: "nithya",
    category: "skin-boosters",
    subcategory: "Type I Collagen Powder",
    price: 1400,
    description: "A type-I collagen powder formulated to support skin structure and quality.",
    image: "img/products/nithya-collagen-powder.webp",
    gallery: ["img/products/nithya-collagen-powder-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-20",
    tags: ["skin booster", "collagen", "1 vial"]
  },
  {
    id: "everline-meso-booster",
    name: "Everline Meso-Booster Complex (1 vial)",
    brand: "everline",
    category: "skin-boosters",
    subcategory: "Meso-Booster Complex",
    price: 1900,
    description: "A multi-active meso-booster complex for skin revitalization sessions.",
    image: "",
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-25",
    tags: ["skin booster", "meso-booster", "1 vial"]
  },
  {
    id: "kiara-reju",
    name: "Kiara Reju (1 vial)",
    brand: "kiara",
    category: "skin-boosters",
    subcategory: "PDRN + HA",
    price: 1900,
    description: "A PDRN and hyaluronic-acid complex formulated for skin rejuvenation.",
    image: "img/products/kiara-reju.webp",
    gallery: ["img/products/kiara-reju-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-05-30",
    tags: ["skin booster", "pdrn", "hyaluronic acid", "1 vial"]
  },
  {
    id: "rrs-long-lasting-crosslinked",
    name: "RRS Long Lasting Cross-Linked HA (1 vial)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "Cross-Linked HA",
    price: 1900,
    description: "A cross-linked hyaluronic-acid skin booster for extended-duration hydration.",
    image: "img/products/rrs-long-lasting-crosslinked.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-04",
    tags: ["skin booster", "cross-linked", "hyaluronic acid", "1 vial"]
  },
  {
    id: "remedium-pdrn",
    name: "Remedium PDRN (1 vial)",
    brand: "remedium",
    category: "skin-boosters",
    subcategory: "PDRN DNA Extract",
    price: 2100,
    description: "A PDRN DNA-extract skin booster formulated to support skin repair.",
    image: "img/products/remedium-pdrn.webp",
    gallery: ["img/products/remedium-pdrn-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-09",
    tags: ["skin booster", "pdrn", "1 vial"]
  },
  {
    id: "hyalift-750-pro",
    name: "Hyalift 750 Pro (750 mg)",
    brand: "rrs",
    category: "skin-boosters",
    subcategory: "HA",
    price: 2400,
    description: "A concentrated hyaluronic-acid skin booster for professional use.",
    image: "img/products/hyalift-750-pro.webp",
    gallery: ["img/products/hyalift-750-pro-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-14",
    tags: ["skin booster", "hyaluronic acid", "750 mg"]
  },
  {
    id: "stem-cell-whitening",
    name: "Stem Cell Whitening Ampoules (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Stem Cell Ampoules",
    price: 1500,
    description: "Whitening-focused stem-cell ampoules formulated for mesotherapy sessions.",
    image: "img/products/stem-cell-whitening.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-19",
    tags: ["mesotherapy", "whitening", "stem cell", "1 box"]
  },
  {
    id: "bella-meso-pdrn",
    name: "Bella Meso-PDRN (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "PDRN Vials",
    price: 1100,
    description: "A PDRN vial set formulated for mesotherapy revitalization sessions.",
    image: "img/products/bella-meso-pdrn.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-24",
    tags: ["mesotherapy", "pdrn", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-fullerene",
    name: "Bella Meso-Fullerene (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Fullerene Vials",
    price: 2500,
    description: "A fullerene-complex vial set formulated for mesotherapy sessions.",
    image: "img/products/bella-meso-fullerene.webp",
    gallery: ["img/products/bella-meso-fullerene-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-06-29",
    tags: ["mesotherapy", "fullerene", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-vitb12",
    name: "Bella Meso-Vit B12 (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Vitamin B12 Vials",
    price: 2500,
    description: "A vitamin B12 vial set formulated for mesotherapy sessions.",
    image: "img/products/bella-meso-vitb12.webp",
    gallery: ["img/products/bella-meso-vitb12-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-04",
    tags: ["mesotherapy", "vitamin b12", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-gluta",
    name: "Bella Meso-Gluta (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Glutathione Vials",
    price: 2500,
    description: "A glutathione vial set formulated for brightening mesotherapy sessions.",
    image: "img/products/bella-meso-gluta.webp",
    gallery: ["img/products/bella-meso-gluta-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-09",
    tags: ["mesotherapy", "glutathione", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-ha18-coll",
    name: "Bella Meso-HA18+Collagen (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "HA + Collagen Vials",
    price: 2500,
    description: "A hyaluronic-acid and collagen vial set formulated for mesotherapy sessions.",
    image: "img/products/bella-meso-ha18-coll.webp",
    gallery: ["img/products/bella-meso-ha18-coll-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-14",
    tags: ["mesotherapy", "hyaluronic acid", "collagen", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-meso-vitc",
    name: "Bella Meso-Vit C (2 ml x 5 vials)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Vitamin C Vials",
    price: 2500,
    description: "A vitamin C vial set formulated for brightening mesotherapy sessions.",
    image: "img/products/bella-meso-vitc.webp",
    gallery: ["img/products/bella-meso-vitc-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-19",
    tags: ["mesotherapy", "vitamin c", "bella", "2 ml x 5 vials"]
  },
  {
    id: "bella-whitening-exosome",
    name: "Bella Whitening Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Whitening Formula",
    price: 2500,
    description: "An exosome-based whitening formula for brightening mesotherapy sessions.",
    image: "img/products/bella-whitening-exosome.webp",
    gallery: ["img/products/bella-whitening-exosome-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-07-24",
    tags: ["mesotherapy", "exosome", "whitening", "bella", "1 vial"]
  },
  {
    id: "bella-hair-growth-exosome",
    name: "Bella Hair Growth Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Hair Complex",
    price: 3000,
    description: "An exosome-based hair complex formulated for scalp mesotherapy sessions.",
    image: "img/products/bella-hair-growth-exosome.webp",
    gallery: ["img/products/bella-hair-growth-exosome-2.webp"],
    featured: false,
    bestseller: true,
    dateAdded: "2026-07-29",
    tags: ["mesotherapy", "exosome", "hair", "bella", "1 vial"]
  },
  {
    id: "bella-antiacne-exosome",
    name: "Bella Anti-Acne Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Anti-Acne",
    price: 3000,
    description: "An exosome-based formula formulated for acne-focused mesotherapy sessions.",
    image: "img/products/bella-antiacne-exosome.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-03",
    tags: ["mesotherapy", "exosome", "anti-acne", "bella", "1 vial"]
  },
  {
    id: "bella-antiage-exosome",
    name: "Bella Anti-Aging Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Anti-Aging",
    price: 3000,
    description: "An exosome-based formula formulated for anti-aging mesotherapy sessions.",
    image: "img/products/bella-antiacne-exosome.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-08",
    tags: ["mesotherapy", "exosome", "anti-aging", "bella", "1 vial"]
  },
  {
    id: "bella-repair-exosome",
    name: "Bella Repair Exosome (1 vial)",
    brand: "bella",
    category: "mesotherapy",
    subcategory: "Exosome Repairing",
    price: 3000,
    description: "An exosome-based repairing formula for post-procedure mesotherapy sessions.",
    image: "img/products/bella-repair-exosome.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-13",
    tags: ["mesotherapy", "exosome", "repair", "bella", "1 vial"]
  },
  {
    id: "hadurage-pdrn-meso",
    name: "Hadurage PDRN Mesotherapy (1 vial)",
    brand: "hadurage",
    category: "mesotherapy",
    subcategory: "PDRN Solution",
    price: 1500,
    description: "A PDRN solution formulated for mesotherapy revitalization sessions.",
    image: "",
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-18",
    tags: ["mesotherapy", "pdrn", "hadurage", "1 vial"]
  },
  {
    id: "hadurage-hair-meso",
    name: "Hadurage Hair Meso (1 vial)",
    brand: "hadurage",
    category: "mesotherapy",
    subcategory: "Hair Growth Solution",
    price: 5000,
    description: "A hair-growth solution formulated for scalp mesotherapy sessions.",
    image: "img/products/hadurage-hair-meso.webp",
    gallery: ["img/products/hadurage-hair-meso-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-23",
    tags: ["mesotherapy", "hair", "hadurage", "1 vial"]
  },
  {
    id: "vitamin-c-ampoules",
    name: "Pure Vitamin C Ampoules (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Vitamin C Ampoules",
    price: 900,
    description: "Pure vitamin C ampoules formulated for brightening mesotherapy sessions.",
    image: "img/products/vitamin-c-ampoules.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-08-28",
    tags: ["mesotherapy", "vitamin c", "1 box"]
  },
  {
    id: "glutathione-vials",
    name: "Glutathione Vials (1 box)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Glutathione",
    price: 900,
    description: "Glutathione vials formulated for brightening mesotherapy sessions.",
    image: "",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-02",
    tags: ["mesotherapy", "glutathione", "1 box"]
  },
  {
    id: "pink-glow-cocktail",
    name: "Pink Glow Cocktail (1 vial)",
    brand: "clinic-select",
    category: "mesotherapy",
    subcategory: "Multi-Ingredient Cocktail",
    price: 7000,
    description: "A multi-ingredient cocktail formulated for radiance-focused mesotherapy sessions.",
    image: "img/products/pink-glow-cocktail.webp",
    gallery: ["img/products/pink-glow-cocktail-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-07",
    tags: ["mesotherapy", "cocktail", "glow", "1 vial"]
  },
  {
    id: "rablanca-peeling",
    name: "Rablanca Peeling Pack Solution (1 kit)",
    brand: "rablanca",
    category: "cold-peeling",
    subcategory: "Peeling Solution",
    price: 1800,
    description: "A cold peeling-pack solution for surface skin renewal without downtime.",
    image: "",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-12",
    tags: ["peeling", "skin renewal", "1 kit"]
  },
  {
    id: "luer-lock-connector",
    name: "Luer Lock Connector (1 unit)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Connector",
    price: 50,
    description: "A Luer-lock connector for use with injectable aesthetic products.",
    image: "img/products/luer-lock-connector.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-17",
    tags: ["disposable", "accessory", "connector", "1 unit"]
  },
  {
    id: "micro-cannula",
    name: "Micro Cannula (1 unit)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Cannula",
    price: 10,
    description: "A micro-cannula for atraumatic delivery of dermal fillers and skin boosters.",
    image: "img/products/micro-cannula.webp",
    featured: false,
    bestseller: true,
    dateAdded: "2026-09-22",
    tags: ["disposable", "accessory", "cannula", "1 unit"]
  },
  {
    id: "fine-injection-needles",
    name: "Fine Injection Needles (Box)",
    brand: "medisupply",
    category: "disposables",
    subcategory: "Needles",
    price: 250,
    description: "Fine disposable injection needles for precise aesthetic procedures.",
    image: "img/products/fine-injection-needles.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-27",
    tags: ["disposable", "accessory", "needle", "box"]
  },
  {
    id: "reluma-lush",
    name: "Reluma Lush",
    brand: "reluma",
    category: "dermal-fillers",
    subcategory: "dermal-fillers",
    price: 2800,
    description: "A dermal filler designed for correcting medium wrinkles and adding balanced volume.",
    image: "img/products/reluma-lush.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["filler", "body", "contouring", "lush", "reluma"]
  },
  {
    id: "reluma-volumie",
    name: "Reluma Volumie",
    brand: "reluma",
    category: "dermal-fillers",
    subcategory: "dermal-fillers",
    price: 2800,
    description: "A dermal filler formulated for facial contouring, cheek volume, and jawline definition.",
    image: "img/products/reluma-volumie.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["filler", "body", "contouring", "volumie", "reluma"]
  },
  {
    id: "reluma-glisse",
    name: "Reluma Glisse",
    brand: "reluma",
    category: "dermal-fillers",
    subcategory: "dermal-fillers",
    price: 2800,
    description: "A lightweight dermal filler targeting fine lines and superficial wrinkles.",
    image: "img/products/reluma-glisse.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["filler", "body", "contouring", "glisse", "reluma"]
  },
  {
    id: "reluma-implant-1-1ml",
    name: "Reluma Implant (1.1ml)",
    brand: "reluma",
    category: "dermal-fillers",
    subcategory: "dermal-fillers",
    price: 2500,
    description: "A high-density dermal filler for deep structural support and facial sculpting.",
    image: "img/products/reluma-implant-1-1ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["filler", "body", "contouring", "implant", "reluma", "1.1ml"]
  },
  {
    id: "reluma-kiss-1-x-1-1ml",
    name: "Reluma Kiss (1 x 1.1ml)",
    brand: "reluma",
    category: "dermal-fillers",
    subcategory: "dermal-fillers",
    price: 1650,
    description: "A specialized dermal filler created for lip augmentation, definition, and hydration.",
    image: "img/products/reluma-kiss-1-x-1-1ml.webp",
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["filler", "body", "contouring", "kiss", "reluma", "1 x 1.1ml"]
  },
  {
    id: "axeniq-100ui",
    name: "AxeniQ 100UI",
    brand: "axeniq",
    category: "botox",
    subcategory: "botox",
    price: 4200,
    description: "A standard 100-unit botulinum toxin injection used to relax facial expression lines.",
    image: "img/products/axeniq-100ui.webp",
    gallery: ["img/products/axeniq-100ui-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["botox", "toxin", "wrinkles", "AxeniQ", "100ui"]
  },
  {
    id: "axeniq-200ui",
    name: "AxeniQ 200UI",
    brand: "axeniq",
    category: "botox",
    subcategory: "botox",
    price: 8000,
    description: "A double-sized 200-unit botulinum toxin injection intended for larger treatment areas.",
    image: "img/products/axeniq-200ui.webp",
    gallery: ["img/products/axeniq-200ui-2.webp"],
    featured: false,
    bestseller: false,
    dateAdded: "2026-09-14",
    tags: ["botox", "toxin", "wrinkles", "AxeniQ", "200ui"]
  }
];
